# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Zhaocheng (Jerry) Zhang 张兆成
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "" # the subpath of the site
url: "https://zhaocheng-zhang.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Vita
    - name: Research
    - name: Teaching

footer:
  show_powered_by: false
  contact:
    - type: email
      name: Email
      value: zz391@cam.ac.uk
    - type: facebook
      name: Facebook
      link: http://facebook.com/profile.php?id=100004522427762
    #- type: wechat
    #  value: YourWeChatUsername
    #  link: "#"
  follow:
    #- type: twitter
    #  name: Twitter
    #  link: http://twitter.com/YourTwitterUsername
    #  username: "@YourTwitterUsername"
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/zhaocheng-jerry-zhang-51192ab5
    - type: github
      name: GitHub
      link: http://github.com/zhaocheng-zhang
    #- type: dribbble
    #  name: Dribbble
    #  link: https://dribbble.com/YourDribbbleUsername
    #- type: rss
    #  name: RSS
    #  link: /feed.xml
    - type: scholar
      name: Scholar
      link: https://scholar.google.com/citations?user=5U-TxWgAAAAJ&hl=en
    - type: orcid
      name: ORCID
      link: http://orcid.org/0000-0001-8803-021X
    - type: researchgate
      name: ResearchGate
      link: https://www.researchgate.net/profile/Zhaocheng-Zhang-4

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
